apply plugin: 'com.android.application'

android {
    compileSdk = 37
    namespace = 'com.androidtweak.rain'

    defaultConfig {
        applicationId = "in.androidtweak.rain"
        minSdk = 23
        targetSdk = 37
        versionCode = 2
        versionName = "1.0.0"
    }

    def keystore = System.getenv("RAIN_KEYSTORE")
    signingConfigs {
        release {
            if (keystore) {
                storeFile = file(keystore)
                storePassword = System.getenv("RAIN_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("RAIN_KEY_ALIAS")
                keyPassword = System.getenv("RAIN_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (keystore) {
                signingConfig = signingConfigs.release
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.2'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'com.github.skydoves:colorpickerview:2.5.0'
}
